
services:
  database:
    image: postgres:14
    container_name: nutrimind_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nutrimind
      POSTGRES_USER: nutrimind_user
      POSTGRES_PASSWORD: nutrimind_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutrimind_network
  redis:
    image: redis:7
    container_name: nutrimind_redis
    ports:
      - "6379:6379"
    networks:
      - nutrimind_network
volumes:
  postgres_data:
networks:
  nutrimind_network: